name: Build
on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      aws-account-id:
        type: string
        required: true
      docker-compose-file:
        type: string
        required: false
        default: docker-compose.yaml
      docker-image-url:
        type: string
        required: true
      docker-tag:
        type: string
        required: true
      docker-push:
        type: boolean
        required: false
        default: false
      unit-test-cmd:
        type: string
        required: false
      behaviour-test-cmd:
        type: string
        required: false
    secrets:
      gh-pat:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKER_IMAGE_URL: ${{ inputs.docker-image-url }}
      DOCKER_TAG: ${{ inputs.docker-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh-pat }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/GitHub
      - name: Create AWS directory
        run: mkdir -p ~/.aws
      - name: Create AWS profile
        run: echo "[default]" > ~/.aws/credentials
      - name: Store AWS access key ID
        run: echo "aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
      - name: Store AWS access key secret
        run: echo "aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      - name: Store AWS session token
        run: echo "aws_session_token = ${{ env.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build
        run: docker-compose -f ${{ inputs.docker-compose-file }} build --force-rm --no-cache --pull
      - name: Tests (unit)
        if: inputs.unit-test-cmd != ''
        run: ${{ inputs.unit-test-cmd }}
      - name: Tests (behaviour)
        if: inputs.behaviour-test-cmd != ''
        run: ${{ inputs.behaviour-test-cmd }}
      - name: Push
        if: inputs.docker-push == true
        run: docker-compose -f ${{ inputs.docker-compose-file }} push
