name: Build
on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      aws-account-id:
        type: string
        required: true
      docker-compose-file:
        type: string
        required: false
        default: docker-compose.yaml
      docker-push:
        type: boolean
        required: false
        default: false
    secrets:
      gh-pat:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_URL: ${{ inputs.docker-image-url }}
      DOCKER_TAG: ${{ inputs.docker-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh-pat }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/GitHub
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build
        run: docker-compose -f ${{ inputs.docker-compose-file }} build --force-rm --no-cache --pull
      - name: Test
        run: make test
      - name: Push
        if: inputs.docker-push == true
        run: docker-compose -f ${{ inputs.docker-compose-file }} push
