name: Build
on:
  workflow_call:
    inputs:
      docker-compose-file:
        type: string
        required: false
        default: ./docker-compose.build.yaml
      docker-image-url:
        type: string
        required: true
      docker-tag:
        type: string
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_URL: ${{ inputs.docker-image-url }}
      DOCKER_TAG: ${{ inputs.docker-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build
        run: docker-compose -f ${{ inputs.docker-compose-file }} build --force-rm --no-cache --pull
      - name: Test
        run: make test
      - name: Push
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        run: docker-compose -f ${{ inputs.docker-compose-file }} push
