name: Build
on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      aws-account-id:
        type: string
        required: true
      docker-compose-file:
        type: string
        required: false
        default: ./docker-compose.yaml
      docker-image-url:
        type: string
        required: true
      docker-push:
        type: boolean
        required: false
        default: false
      kms-image-name:
        type: string
        required: false
        default: kms
      kms-image-version:
        type: string
        required: false
        default: latest
      kms-key-name:
        type: string
        required: false
      kms-encrypted-dir:
        type: string
        required: false
      kms-decrypted-dir:
        type: string
        required: false
      unit-test-cmd:
        type: string
        required: false
      behaviour-test-cmd:
        type: string
        required: false
    secrets:
      ghcr-pat:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKER_IMAGE_URL: ${{ inputs.docker-image-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: lickdltd/setup-action@v1
        with:
          ghcr-pat: ${{ secrets.ghcr-pat }}
          aws-region: ${{ inputs.aws-region }}
          aws-account-id: ${{ inputs.aws-account-id }}
      - name: Build
        env:
          DOCKER_TAG: ${{ steps.setup.outputs.git-hash-short }}
        run: docker-compose -f ${{ inputs.docker-compose-file }} build
      - name: Decrypt environment variables
        if: inputs.kms-key-name != '' && inputs.kms-encrypted-dir != '' && inputs.kms-decrypted-dir != ''
        run: |
          docker run --rm \
          -v ~/.aws:/root/.aws:ro \
          -v ${{ inputs.kms-encrypted-dir }}:/tmp/encrypted \
          -v ${{ inputs.kms-decrypted-dir }}:/tmp/decrypted \
          ghcr.io/${{ github.repository_owner }}/${{ inputs.kms-image-name }}:${{ inputs.kms-image-version }} decrypt \
            --key ${{ inputs.kms-key-name }} \
            --input-dir /tmp/encrypted \
            --output-dir /tmp/decrypted
      - name: Tests (unit)
        if: inputs.unit-test-cmd != ''
        env:
          DOCKER_TAG: ${{ steps.setup.outputs.git-hash-short }}
        run: ${{ inputs.unit-test-cmd }}
      - name: Tests (behaviour)
        if: inputs.behaviour-test-cmd != ''
        env:
          DOCKER_TAG: ${{ steps.setup.outputs.git-hash-short }}
        run: ${{ inputs.behaviour-test-cmd }}
      - name: Push
        if: inputs.docker-push == true
        env:
          DOCKER_TAG: ${{ steps.setup.outputs.git-hash-short }}
        run: docker-compose -f ${{ inputs.docker-compose-file }} push
