name: Deploy
on:
  workflow_call:
    inputs:
      docker-compose-file:
        type: string
        required: false
        default: ./docker-compose.ansible.yaml
      ansible-env:
        type: string
        required: true
    secrets:
      gh-pat:
        required: true
      ssh-private-key:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ANSIBLE_ENV: ${{ inputs.ansible-env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh-pat }}
      - name: Setup SSH key
        run: echo "${{ secrets.ssh-private-key }}" > ./id_rsa
      - name: Setup SSH known hosts
        run: ssh-keyscan github.com > ./known_hosts
      - name: Setup SSH permissions
        run: chmod 600 ./id_rsa ./known_hosts
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: eu-west-1
      - name: Install ansible requirements
        run: docker-compose -f ${{ inputs.docker-compose-file }} run ansible ansible-galaxy install -r requirements.yaml
      - name: Deploy using anisble
        run: docker-compose -f ${{ inputs.docker-compose-file }} run ansible ansible-playbook deploy.yaml
