name: Lint
on:
  workflow_call:
    inputs:
      default-branch:
        type: string
        required: false
        default: main
      validate-all:
        type: boolean
        required: false
        default: false
      regex-exclude:
        type: string
        required: false
        default: "(.*test/.*|.*.encrypted)"
    secrets:
      github-token:
        required: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all }}
          VALIDATE_EDITORCONFIG: false
          VALIDATE_ENV: false
          VALIDATE_JSCPD: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_TERRAFORM_TFLINT: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          IGNORE_GITIGNORED_FILES: true
          FILTER_REGEX_EXCLUDE: ${{ inputs.regex-exclude }}
