name: Stale
on:
  workflow_call:
    inputs:
      days-before-issue-stale:
        type: number
        required: false
        default: 30
      days-before-pr-stale:
        type: number
        required: false
        default: 30
      days-before-issue-close:
        type: number
        required: false
        default: 10
      days-before-pr-close:
        type: number
        required: false
        default: 10
jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: "This issue is stale because it has been open ${{ inputs.days-before-issue-stale }} days with no activity. Remove stale label or comment or this will be closed in ${{ inputs.days-before-issue-close }} days."
          stale-pr-message: "This PR is stale because it has been open ${{ inputs.days-before-pr-stale }} days with no activity. Remove stale label or comment or this will be closed in ${{ inputs.days-before-pr-close }} days."
          close-issue-message: "This issue was closed because it has been stalled for ${{ inputs.days-before-issue-close }} days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for ${{ inputs.days-before-pr-close }} days with no activity."
          days-before-issue-stale: ${{ inputs.days-before-issue-stale }}
          days-before-pr-stale: ${{ inputs.days-before-pr-stale }}
          days-before-issue-close: ${{ inputs.days-before-issue-close }}
          days-before-pr-close: ${{ inputs.days-before-pr-close }}
