name: Terraform Upgrade
on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      aws-account-id:
        type: string
        required: true
      working-directory:
        type: string
        required: true
      terraform-version:
        type: string
        required: false
        default: "1.1.7"
    secrets:
      ssh-private-key:
        required: false
jobs:
  terraform:
    name: Terraform Upgrade
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: lickdltd/setup-action@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-account-id: ${{ inputs.aws-account-id }}
          ssh-private-key: ${{ secrets.ssh-private-key }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Initialise
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
        run: terraform init -upgrade
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: terraform-upgrade
          branch-suffix: random
          commit-message: Upgrade Terraform dependencies (${{ inputs.working-directory }})
          title: Upgrade Terraform dependencies for ${{ inputs.working-directory }}
          body: Automated Terraform dependency upgrades for ${{ inputs.working-directory }}
